# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import static.staticValues as staticValues

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        
        #메인 화면 색상py
        self.setStyleSheet("color: black;"
                        "background-color: white")
                        
        MainWindow.resize(500, 320)
        MainWindow.setMinimumSize(QtCore.QSize(500, 320))
        MainWindow.setMaximumSize(QtCore.QSize(500, 320))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 30, 91, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.editFilePath = QtWidgets.QLineEdit(self.centralwidget)
        self.editFilePath.setGeometry(QtCore.QRect(40, 62, 281, 21))
        self.buttonOpenWordsFile = QtWidgets.QPushButton(self.centralwidget)
        self.buttonOpenWordsFile.setGeometry(QtCore.QRect(350, 60, 111, 41))
        self.buttonOpenWordsFile.setStyleSheet(staticValues.buttonStyleSheet)
        self.buttonOpenWordsFile.setFont(staticValues.buttonFont)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 120, 64, 15))
        self.label_2.setFont(font)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 160, 64, 15))
        self.label_3.setFont(font)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(50, 200, 71, 16))
        self.label_4.setFont(font)
        self.editFrom = QtWidgets.QLineEdit(self.centralwidget)
        self.editFrom.setGeometry(QtCore.QRect(100, 160, 81, 21))
        self.editTo = QtWidgets.QLineEdit(self.centralwidget)
        self.editTo.setGeometry(QtCore.QRect(230, 160, 81, 21))
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(200, 160, 21, 20))
        self.label_5.setFont(font)
        self.editNumOfWord = QtWidgets.QLineEdit(self.centralwidget)
        self.editNumOfWord.setGeometry(QtCore.QRect(230, 200, 81, 21))
        self.buttonGenTest = QtWidgets.QPushButton(self.centralwidget)
        self.buttonGenTest.setGeometry(QtCore.QRect(350, 260, 111, 41))
        self.buttonGenTest.setStyleSheet(staticValues.buttonStyleSheet)
        self.buttonGenTest.setFont(staticValues.buttonFont)
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(100, 113, 201, 31))
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.RB_English = QtWidgets.QRadioButton(self.layoutWidget)
        self.RB_English.setChecked(True)
        self.horizontalLayout.addWidget(self.RB_English)
        self.RB_Korean = QtWidgets.QRadioButton(self.layoutWidget)
        self.horizontalLayout.addWidget(self.RB_Korean)
        self.RB_EK = QtWidgets.QRadioButton(self.layoutWidget)
        self.horizontalLayout.addWidget(self.RB_EK)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle("TESTMAKER")
        self.label.setText("단어장 파일")
        self.buttonOpenWordsFile.setText("단어장 열기")
        self.label_2.setText("조건")
        self.label_3.setText("회차")
        self.label_4.setText("단어 개수")
        self.label_5.setText("~")
        self.buttonGenTest.setText("시험지 생성")
        self.RB_English.setText("영어")
        self.RB_Korean.setText("한글")
        self.RB_EK.setText("혼합")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
